[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["rm -f package-lock.json", "pnpm config set store-dir /app/.pnpm-store-v2", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]
