<template>
  <div class="space-y-6">
    <div>
      <h2 class="text-xl font-semibold" style="color: var(--text-primary)">
        {{ t('admin.pages.devices.title', 'Device Management') }}
      </h2>
      <p class="mt-1 text-sm" style="color: var(--text-secondary)">
        {{ t('admin.pages.devices.subtitle', 'Manage offline activation codes for your POS devices.') }}
      </p>
    </div>

    <div class="rounded-2xl p-6" style="background: var(--surface-1); border: 1px solid var(--surface-border); box-shadow: var(--card-shadow)">
      <h3 class="text-base font-medium mb-4" style="color: var(--text-primary)">
        Offline Activation
      </h3>
      
      <div v-if="!activationCode" class="space-y-4 max-w-xl">
        <p class="text-sm" style="color: var(--text-secondary)">
          To activate a POS device without an internet connection, enter the Request Code generated by the device below.
        </p>
        
        <div>
          <label class="block text-sm font-medium mb-1.5" style="color: var(--text-primary)">Request Code</label>
          <textarea
            v-model="requestCode"
            rows="3"
            class="ui-input w-full font-mono text-sm"
            placeholder="Paste the Request Code here..."
          ></textarea>
        </div>

        <div v-if="error" class="text-sm text-red-500 font-medium">
          {{ error }}
        </div>

        <div class="flex justify-end pt-2">
          <button
            class="ui-btn ui-btn--primary"
            :disabled="!requestCode.trim() || pending"
            @click="generateActivationCode"
          >
            <Icon v-if="pending" name="lucide:loader-2" class="w-4 h-4 mr-2 animate-spin" />
            <Icon v-else name="lucide:key" class="w-4 h-4 mr-2" />
            Generate Activation Code
          </button>
        </div>
      </div>

      <div v-else class="space-y-4">
        <div class="p-4 rounded-xl" style="background: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.2)">
          <div class="flex items-center gap-3 text-emerald-600 mb-2">
            <Icon name="lucide:check-circle-2" class="w-5 h-5" />
            <span class="font-semibold">Activation Code Generated Successfully</span>
          </div>
          <p class="text-sm" style="color: var(--text-secondary)">
            Copy the code below and paste it into your offline POS device to complete the activation process.
          </p>
        </div>

        <div class="relative mt-4">
          <textarea
            readonly
            rows="4"
            class="ui-input w-full font-mono text-sm bg-gray-50/50"
            :value="activationCode"
          ></textarea>
          <button
            @click="copyCode"
            class="absolute top-3 right-3 ui-btn ui-btn--sm ui-btn--secondary"
          >
            <Icon :name="copied ? 'lucide:check' : 'lucide:copy'" class="w-4 h-4" />
            {{ copied ? 'Copied!' : 'Copy' }}
          </button>
        </div>

        <div class="flex justify-end pt-4">
          <button class="ui-btn ui-btn--secondary" @click="reset">
            Activate Another Device
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '~/stores/auth'
import { useI18n } from 'vue-i18n'

definePageMeta({
  middleware: 'auth',
  layout: 'admin',
})

const { t } = useI18n({ useScope: 'global' })
const authStore = useAuthStore()

const requestCode = ref('')
const activationCode = ref('')
const error = ref('')
const pending = ref(false)
const copied = ref(false)

async function generateActivationCode() {
  if (!requestCode.value.trim()) return

  error.value = ''
  pending.value = true

  try {
    const token = authStore.token?.value ?? (authStore as any).token
    const res = await $fetch<any>('/api/activation/offline', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`
      },
      body: {
        requestCode: requestCode.value.trim()
      }
    })

    if (res.activationToken) {
      activationCode.value = res.activationToken
    } else {
      error.value = 'Failed to generate token. Please check your Request Code.'
    }
  } catch (err: any) {
    error.value = err.data?.error || err.message || 'An error occurred during activation.'
  } finally {
    pending.value = false
  }
}

function copyCode() {
  navigator.clipboard.writeText(activationCode.value)
  copied.value = true
  setTimeout(() => copied.value = false, 2000)
}

function reset() {
  requestCode.value = ''
  activationCode.value = ''
  error.value = ''
  copied.value = false
}
</script>
