// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOfxF6pG8s7AkEbEaypPfsmpBrshvnBc',
    appId: '1:173108648235:android:d8acce0ea06929c067cd6e',
    messagingSenderId: '173108648235',
    projectId: 'swekly-45280',
    storageBucket: 'swekly-45280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KkYWNF_J_Tv0vSlF5u_AVv_Iytbd2q4',
    appId: '1:173108648235:ios:f33656dd368bb1f567cd6e',
    messagingSenderId: '173108648235',
    projectId: 'swekly-45280',
    storageBucket: 'swekly-45280.firebasestorage.app',
    iosBundleId: 'com.lyazz.mysaas.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8KkYWNF_J_Tv0vSlF5u_AVv_Iytbd2q4',
    appId: '1:173108648235:ios:f33656dd368bb1f567cd6e',
    messagingSenderId: '173108648235',
    projectId: 'swekly-45280',
    storageBucket: 'swekly-45280.firebasestorage.app',
    iosBundleId: 'com.lyazz.mysaas.admin',
  );
}
